version: "3"

services:
  app:
    image: nave3/laravel-template:app-8.x_php8.0
    container_name: laravel8.x_app
    build:
      context: ..
      dockerfile: app/php8_0.Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - db
    tty: true
